### ISSUE TITLE
How can I use it while keeping compatible with IE8?

### ISSUE THREAD

**Issue by infinnie** [gaearon/react-dnd-html5-backend#3]
Recently I’ve been dealing with compatibility issues of a project using React-DnD. Now exactly because of the code from react-dnd-html5-backend, the web app ceases to work in IE8. What can I do?

**Comment by gaearon** [comment]
Maybe due to [getter usage](https://github.com/gaearon/react-dnd-html5-backend/blob/master/src/NativeDragSources.js#L45)? You can try removing it. If it works, you can add a feature check like [canDefineProperty](https://github.com/facebook/react/blob/master/src/shared/utils/canDefineProperty.js) and change the code to use it.

**Comment by infinnie** [comment]
Seems a problem caused by addEventListener :(
Maybe it can be overcome by hijacking the addEventListener/removeEventListener properties to jQuery calls I guess :sleeping:

**Comment by gaearon** [comment]
It is not wise to depend on jQuery for the sake of two methods. jQuery isn't magic. Take a look at what it does and do the same. For example, maybe IE8 needs `node.attachEvent` instead or something similar.

**Comment by infinnie** [comment]
Yup :)

**Comment by gaearon** [comment]
Closing. Please feel free to create a fork doing this. We don't plan to officially support IE8 in this repo.
